# jira-postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: jira
  labels:
    app: jira-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: jira-postgres